### ISSUE TITLE
Weeks duration not supported

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#10]
Weeks duration calculation should be supported:

define WeekExample1: weeks between @2012-03-10T22:05:09 and @2012-03-20T07:19:33

Currently gives "Invalid duration precision"

**Comment by c-schuler** [comment]
Fixed here:
https://github.com/DBCG/cql_engine/commit/23eacf1925f532320a1c7c01faa52e6ac3a5fb92
