### ISSUE TITLE
Change default precision behavior for date/time comparison

### ISSUE THREAD

**Issue by c-schuler** [DBCG/cql_engine#106]
Currently, date/time comparison operators default to millisecond precision when the precision is not specified. This behavior is not ideal because it will often lead to null results for expressions and puts an unnecessary burden on the developer. A more sensible approach would be to set the precision to the least precise argument passed into the operator when precision is not specified. The spec is unclear on this subject and should be clarified.

**Comment by brynrhodes** [comment]
Agree with this except it should be "set the precision to the most precise argument".

**Comment by c-schuler** [comment]
Note that this issue should be applied to the 1.3 version of the engine.

**Comment by JPercival** [comment]
Already completed.
