### ISSUE TITLE
Add option for ExpressionRefs to be cached within a given Patient context

### ISSUE THREAD

**Issue by nkarip** [DBCG/cql_engine#11]
If an Expression is referenced multiple times, have option to evaluate the expression once and use the computed value for each future reference within the same Patient context. Without this, performance is impacted by expressions with Retrieve operations being run multiple times to extract same data.

Per Bryn, 'CQL is explicitly designed as a functional language so that this type of caching will work with evaluations'.

**Comment by c-schuler** [comment]
Fixed here: 
9e2556576485d9c43c3ed9bdad588d64c7f7abba

Description:
Will save the results of the 10 most recently accessed expressions.

Usage:
context.setExpressionCaching(true);

See example here:
 https://github.com/DBCG/cql_engine/blob/9e2556576485d9c43c3ed9bdad588d64c7f7abba/cql-engine/src/test/java/org/opencds/cqf/cql/execution/CqlDateTimeOperatorsTest.java#L27

This is available in 1.2.3-SNAPSHOT of the engine.
