### ISSUE TITLE
DateFrom does not extract the Date component correctly

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#12]
In this CQL:

    define DateTime1: @2012-03-10T10:20:00
    define DateTime2: @2013-03-10T09:20:00
    define DurationInYears: years between (date from DateTime1) and (date from DateTime2)

DurationInYears should return 1, but it returns 0.

**Comment by c-schuler** [comment]
Resolved: 
https://github.com/DBCG/cql_engine/commit/1b4747de6d837d896c31c34fe5485cb17c760bbb

Test here:
https://github.com/DBCG/cql_engine/commit/6d5007c956271eebfa2ab3e237897be38ef121d7#diff-3e77c0680c3fd657fe2b0dd84ac42ab0
