### ISSUE TITLE
Consider running the same tests that the JavaScript engine uses

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#122]
The JavaScript engine defines a set of unit tests for CQL [here](https://github.com/cqframework/cql-execution/tree/master/test/elm)

Each subfolder contains:
    data.cql:  contains CQL snippets for test
    data.coffee: the corresponding ELM JSON stuffed into a coffee file
    test.coffee: the actual tests that load up the CQL snippets, execute them, then make assertions against them
    (potentially other files as well, as needed)

Note that the data.cql files contain special annotations in the comments that identify (and separate) the tests.  We run these through some Java code before compiling them to ELM.  The custom Java code is [here](https://github.com/cqframework/cql-execution/blob/master/test/generator/src/main/java/CoffeeScriptTestDataGenerator.java).

**Comment by duncand** [comment]
Note that I intend to make some solid improvements to the XML test suite with the Engine sometime in the next few weeks, finishing the job as it were.  Ostensibly that format is better than the verbose .coffee examples given above.

**Comment by duncand** [comment]
I might even be starting the work this weekend, in fact.
