### ISSUE TITLE
Docker containerization (for HSPC demo).

### ISSUE THREAD

**Issue by preston** [DBCG/cql_engine#13]
I've love to demo automated deployment of this at HSPC this month. Doing so essentially just requires Docker containerization and pushing releases image(s) to a public repo, such Docker Hub. Would it be possible to get a Dockerfile to do this? I can get the server registered and can test deployment.

**Comment by preston** [comment]
For an example of how this went down in a similar project: https://github.com/mitre/cql-translation-service/issues/1

Building the container is usually fairly straightforward. Sticky points are usually related to how runtime configuration is passed in, which *must* be via runtime environment variables since (1) images are immutable, (2) configuration details such as database URLs, FHIR endpoints etc cannot be known at compile time, and (3) containers are completely agnostic to any language- or framework-specific voodoo. I promise it makes a ton of sense to do it this way, but may require a patch to make sure that any/all configuration is friendly to the interoperable service container approach. :)

Please let me know if you think this should be possible for the meeting in a few weeks!

**Comment by brynrhodes** [comment]
I love the idea and we'd be happy to help. We've done a little bit of this with the measure processor (see here for example: https://hub.docker.com/r/polyakov/cql-measure-processor/). For the engine, what were you thinking as a host for a deployment demo?

**Comment by preston** [comment]
@brynrhodes On AWS in the HSPC CDS Sandbox, probably on the ASU host since the agent daemon isn't really stable yet.

**Comment by JPercival** [comment]
Issue out of date. There are containers providing an interface to the cql-engine at:

https://hub.docker.com/r/polyakov/cql-measure-processor/
https://hub.docker.com/r/harmoniq/cqf-ruler

We are working on a slimmer, engine-focused service and container at:

https://github.com/DBCG/cql_execution_service
