### ISSUE TITLE
NotImplementedException for CodeRef expression

### ISSUE THREAD

**Issue by nkarip** [DBCG/cql_engine#14]
CodeRef expression defined in clinicalexpression.xsd gives NotImplementedExpression. I think this is still a valid expression in the language, see cqframework repository Examples/Zika/zika-virus-intervention-logic.xml for example. 
org.apache.commons.lang3.NotImplementedException: evaluate not implemented for class CodeRef
	at org.opencds.cqf.cql.elm.execution.Executable.evaluate(Executable.java:11)

Expect evaluation of CodeRef expression should return org.opencds.cqf.cql.runtime.Code object from named CodeDef element in order to work with RetrieveEvaluator -
                Object codesResult = this.getCodes().evaluate(context);
                if (codesResult instanceof Code) {...}

**Comment by c-schuler** [comment]
Resolved: https://github.com/DBCG/cql_engine/commit/7590d49b57f3bc1e8596d4b67732140209e89d50
Tests: https://github.com/DBCG/cql_engine/blob/7590d49b57f3bc1e8596d4b67732140209e89d50/cql-engine-fhir/src/test/java/org/opencds/cqf/cql/data/fhir/TestCodeRef.java#L47
Fix is in 1.2.5-SNAPSHOT version of engine.
