### ISSUE TITLE
Distinct operator not working with resources.

### ISSUE THREAD

**Issue by jscherer-motivemi** [DBCG/cql_engine#151]
If you have duplicated resources in a list and apply the distinct operator, the duplicates are not removed.

**Comment by jscherer-motivemi** [comment]
Chris, is this issue address in v1.2.58 or v1.3.x of the engine?

Thank you for the update.
Julie

**Comment by c-schuler** [comment]
Hi Julie,

This issue should be resolved in both engine versions using the latest snapshots.
We resolved this issue by implementing equals/equivalence methods in the DataProvider interface. By using the DataProviders provided in the cql-engine-fhir project, the HAPI type equivalence should already be provided. Let me know if you run into any issues.

Thanks,
Chris

**Comment by c-schuler** [comment]
@jscherer-motivemi : Is there any follow-up to this issue or am I free to close?

**Comment by jscherer-motivemi** [comment]
@c-schuler , we are regressing this issue against the 1.3.8 instance. Can I update you on the status next week?

**Comment by c-schuler** [comment]
Please do and thank you.

**Comment by jscherer-motivemi** [comment]
@c-schuler, we validated this fix. Thank you.

**Comment by jscherer-motivemi** [comment]
@c-schuler, we validated this fix. Thank you.
