### ISSUE TITLE
org.hl7.elm.r1.Library vs org.cqframework.cql.elm.execution.Library

### ISSUE THREAD

**Issue by sotty** [DBCG/cql_engine#154]
I am trying to use the official CQL2Elm Translator in combination with this CQL engine: both provide distinct XSD-driven implementation of the ELM AST classes, which requires an (apparently?) unnecessary XML roundtrip in order to chain the two tools.
Are there any deeper reasons why both can't use a common module?

**Comment by brynrhodes** [comment]
The technical reason is that the CQL-to-ELM side classes extend [Trackable](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/elm/src/main/java/org/cqframework/cql/elm/tracking/Trackable.java) while the engine classes all extend [Executable](https://github.com/DBCG/cql_engine/blob/master/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/Executable.java). The reason for this separation is that the translator doesn't (and shouldn't) know about execution, and the engine doesn't (and shouldn't) know about translation.

I do agree that it's in theory an unnecessary round-trip, but the alternative was a visitor pattern which would incur an unnecessarily high run-time cost. Current design rationale is documented [here](https://github.com/DBCG/cql_engine/blob/master/cql-engine/src/main/java/org/opencds/cqf/cql/execution/CqlEngine.java). Totally open to alternatives, just didn't want the run-time cost of determining node type.

**Comment by sotty** [comment]
Bryn, thanks!
I had noticed the full hierarchies myself after posting this, and I totally agree with the separation between the engine and the translator.

It may be worthwhile to create dedicated constructors - I think it would be ok for the engine to be 'aware' of the translator - especially since it is promoted as a CQL engine?

I have also seen 'inversion of control' based visitors, like this one, but I have no idea of what the relative performance would be
https://github.com/mariofusco/from-gof-to-lambda/tree/master/src/main/java/org/mfusco/fromgoftolambda/examples/visitor
