### ISSUE TITLE
Passing in Parameters

### ISSUE THREAD

**Issue by jduke99** [DBCG/cql_engine#158]
Sorry if this is a simple question, but how do I pass in parameters to the CQL engine (/cql/evaluate)?

eg, I have a parameter in my CQL like:

parameter "MyString" String

and I want to pass in this string when I execute the CQL.  

Thanks!

**Comment by brynrhodes** [comment]
Hi @jduke99 , there is a [setParameter](https://github.com/DBCG/cql_engine/blob/master/cql-engine/src/main/java/org/opencds/cqf/cql/execution/Context.java#L431) method on the context, so when you've established the context for the engine, you can set parameters prior to evaluating.

**Comment by MikeRileyGTRI** [comment]
@brynrhodes I'm a co-worker of @jduke99, and primarily, this is actually an issue with cql_execution_service. The service doesn't allow for parameter passing. I have a pull request I need to push up to that repository that can handle this issue, and it would be great to have it accepted!

**Comment by brynrhodes** [comment]
@MikeRileyGTRI , that would be fantastic, thank you!
