### ISSUE TITLE
ToDateTimeEvaluator errors when operand is already a DateTime instance 

### ISSUE THREAD

**Issue by raman-sv** [DBCG/cql_engine#173]
Not entirely sure why it's being called if operand is already a DateTime

**Comment by raman-sv** [comment]
diff --git a/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/ToDateTimeEvaluator.java b/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/ToDateTimeEvaluator.java
index c6d37d1e..e50b7c34 100644
--- a/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/ToDateTimeEvaluator.java
+++ b/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/ToDateTimeEvaluator.java
@@ -46,6 +46,12 @@ public class ToDateTimeEvaluator extends org.cqframework.cql.elm.execution.ToDat
                 return null;
             }
         }
+        
+        /*
+         * need to handle the case where the operand is already a DateTime
+         */
+        if (operand instanceof DateTime)
+               return operand;
 
         if (operand instanceof Date) {
             return new DateTime(TemporalHelper.getDefaultOffset(), ((Date) operand).getDate().getYear(), ((Date) operand).getDate().getMonthValue(), ((Date) operand).getDate().getDayOfMonth(), 0, 0, 0, 0);
[ToDateTimeEvaluator_java_diff.txt](https://github.com/DBCG/cql_engine/files/3070277/ToDateTimeEvaluator_java_diff.txt)

**Comment by c-schuler** [comment]
Yeah, that is odd... I will add a check for that. Thanks!

Could you provide the code snippet that brought this issue to light so I can add it to the test suite?

**Comment by raman-sv** [comment]
CQL that caused the error:
`AgeInYearsAt (Enc.period.start.value)`

Error message:
`Cannot perform the ToDateTime operation with argument of type org.opencds.cqf.cql.runtime.DateTime`

**Comment by raman-sv** [comment]
This is the change I made locally to get it to work:
```
diff --git a/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/ToDateTimeEvaluator.java b/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/ToDateTimeEvaluator.java
index c6d37d1e..e50b7c34 100644
--- a/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/ToDateTimeEvaluator.java
+++ b/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/ToDateTimeEvaluator.java
@@ -46,6 +46,12 @@ public class ToDateTimeEvaluator extends org.cqframework.cql.elm.execution.ToDat
                 return null;
             }
         }
+
+        /*
+         * need to handle the case where the operand is already a DateTime
+         */
+        if (operand instanceof DateTime)
+               return operand;

         if (operand instanceof Date) {
             return new DateTime(TemporalHelper.getDefaultOffset(), ((Date) operand).getDate().getYear(), ((Date) operand).getDate().getMonthValue(), ((Date) operand).getDate().getDayOfMonth(), 0, 0, 0, 0);
```

**Comment by brynrhodes** [comment]
This is the same root cause as #174
