### ISSUE TITLE
DurationBetweenEvaluator does not handle case with mixed Date and DateTime inputs 

### ISSUE THREAD

**Issue by raman-sv** [DBCG/cql_engine#174]

**Comment by raman-sv** [comment]
diff --git a/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/DurationBetweenEvaluator.java b/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/DurationBetweenEvaluator.java
index 41660c85..9cacb1b0 100644
--- a/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/DurationBetweenEvaluator.java
+++ b/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/DurationBetweenEvaluator.java
@@ -63,6 +63,19 @@ public class DurationBetweenEvaluator extends org.cqframework.cql.elm.execution.
                         duration(left, rightUncertainInterval.getEnd(), isWeeks ? Precision.WEEK : precision), true
                 ).setUncertain(true);
             }
+            
+            /*
+             * From comments above: When this operator is called with both Date and DateTime inputs, the Date values will be implicitly converted to
+                * DateTime as defined by the ToDateTime operator.
+                * This scenario was not handled
+                * Here's a workaround - better approach might be to re-use ToDateTime code rather than in-lining it here
+             */
+            
+            if (left instanceof DateTime && right instanceof Date) 
+               right = new DateTime(TemporalHelper.getDefaultOffset(), ((Date) right).getDate().getYear(), ((Date) right).getDate().getMonthValue(), ((Date) right).getDate().getDayOfMonth(), 0, 0, 0, 0);
+
+            if (left instanceof Date && right instanceof DateTime)
+               left = new DateTime(TemporalHelper.getDefaultOffset(), ((Date) left).getDate().getYear(), ((Date) left).getDate().getMonthValue(), ((Date) left).getDate().getDayOfMonth(), 0, 0, 0, 0);    
 
             if (left instanceof DateTime && right instanceof DateTime) {
                 return isWeeks

**Comment by c-schuler** [comment]
As per the spec, the translator should promote the Date to DateTime. 

Is this causing an error for you? Could you provide more context?

**Comment by raman-sv** [comment]
Error message:
Execution of CQL or ELM statement named [Adult] failed due to error:
Cannot perform DifferenceBetween operation with arguments of type 'org.opencds.cqf.cql.runtime.DateTime' and 'org.opencds.cqf.cql.runtime.Date'.
 
CQL:
```
define Adult:
     AgeInYearsAt(Today()) >= 18
```
 
ELM:
```
     <def name="Adult" context="Patient" accessLevel="Public">
         <expression xsi:type="GreaterOrEqual">
            <operand precision="Year" xsi:type="CalculateAgeAt">
               <operand path="birthDate.value" xsi:type="Property">
                  <source name="Patient" xsi:type="ExpressionRef"/>
               </operand>
               <operand xsi:type="Today"/>
            </operand>
            <operand valueType="t:Integer" value="18" xsi:type="Literal"/>
         </expression>
      </def>
```

**Comment by raman-sv** [comment]
Here's the change I made to get it to work locally. I am not able to do PRs to directly send over these changes for your review.
```
diff --git a/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/DurationBetweenEvaluator.java b/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/DurationBetweenEvaluator.java
index 41660c85..9cacb1b0 100644
--- a/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/DurationBetweenEvaluator.java
+++ b/cql-engine/src/main/java/org/opencds/cqf/cql/elm/execution/DurationBetweenEvaluator.java
@@ -63,6 +63,19 @@ public class DurationBetweenEvaluator extends org.cqframework.cql.elm.execution.
duration(left, rightUncertainInterval.getEnd(), isWeeks ? Precision.WEEK : precision), true
).setUncertain(true);
}
+
```

**Comment by raman-sv** [comment]
Here's the code snippet that was added locally (the diff above didn't show up correctly):
```
            
            /*
             * From comments above: When this operator is called with both Date and DateTime inputs, the Date values will be implicitly converted to
    		 * DateTime as defined by the ToDateTime operator.
    		 * This scenario was not handled
    		 * Here's a workaround - better approach might be to re-use ToDateTime code rather than in-lining it here
             */
            
            if (left instanceof DateTime && right instanceof Date) 
            	right = new DateTime(TemporalHelper.getDefaultOffset(), ((Date) right).getDate().getYear(), ((Date) right).getDate().getMonthValue(), ((Date) right).getDate().getDayOfMonth(), 0, 0, 0, 0);

            if (left instanceof Date && right instanceof DateTime)
            	left = new DateTime(TemporalHelper.getDefaultOffset(), ((Date) left).getDate().getYear(), ((Date) left).getDate().getMonthValue(), ((Date) left).getDate().getDayOfMonth(), 0, 0, 0, 0);
            
```

**Comment by brynrhodes** [comment]
@raman-sv , what version of the CQL-to-ELM translator are you using? The translator should be implicitly converting so that both arguments are the same type so that the engine doesn't have to deal with the added complexity of type testing those cases, and there are some known issues around this, but it sounds like maybe there is still a problem with the translator?

**Comment by raman-sv** [comment]
@brynrhodes, I'm using version 1.3.14 of cql-to-elm.
`
		<dependency>
			<groupId>info.cqframework</groupId>
			<artifactId>cql-to-elm</artifactId>
			<version>1.3.14</version>
		</dependency>
`

**Comment by brynrhodes** [comment]
Digging further, this is actually a problem with the Base provider in that it is returning a DateTime from a FHIR.date type.
