### ISSUE TITLE
NotImplementedException for Filter expression

### ISSUE THREAD

**Issue by nkarip** [DBCG/cql_engine#19]
Using Filter expression (example below) throws not yet implemented exception. 
```
<operand xsi:type="Filter" scope="R">
   <source name="FluTests" xsi:type="ExpressionRef"/>
   <condition xsi:type="InValueSet">
      <code path="code.coding" scope="R" xsi:type="Property" />					
      <valueset name="InfluenzaMolecular" xsi:type="ValueSetRef"/>
   </condition>
</operand>	
```

**Comment by c-schuler** [comment]
Resolved: https://github.com/DBCG/cql_engine/commit/72ca653665d337a6cee165d5c0641b5a7d87f621
Get the 1.2.15-SNAPSHOT version of the engine for Filter evaluation.

I haven't tested this very much yet... I will leave the issue open in case you run into any problems.

**Comment by nkarip** [comment]
Tested with the script below (where the ExpressionRef is a Query against Observations) and seems to be working.

<operand xsi:type="Filter" scope="R">
	<source name="FluTests" xsi:type="ExpressionRef"/>
	<condition xsi:type="InValueSet">
		<code xsi:type="ToConcept">
			<operand path="code.coding" scope="R" xsi:type="Property"/>
		</code>				
		<valueset name="InfluenzaMolecular" xsi:type="ValueSetRef"/>
	</condition>
</operand>

**Comment by c-schuler** [comment]
Great! Closing this...
