### ISSUE TITLE
cql-engine-fhir FileBasedFhirProvider does not handle interval datePath

### ISSUE THREAD

**Issue by nkarip** [DBCG/cql_engine#20]
According to clinicalexpression.xsd, dateProperty may be a DateTime or Interval. If both dateProperty and dateRange are intervals then resource should be included in results if entire dateProperty interval is included in the date range. FileBasedFhirProvider currently only handles scenario where dateProperty is a datetime, not an interval.

The following code works in my testing.

`
                    if (temp instanceof DateTime) {
                        date = (DateTime)temp;
                    }
                    else if (temp instanceof DateTimeType) {
                        date = toDateTime((DateTimeType)temp);
                    }
                    else if (temp instanceof Interval) {
                    	dateInterval = (Interval)temp;
                    }

                    if (date != null && InEvaluator.in(date, expanded)) {
                        results.add(res);
                    }
                    else if(dateInterval != null && (Boolean)IncludesEvaluator.includes(expanded, dateInterval)){                    	
                    	results.add(res);
                    }
                    else {
                        includeRes = false;
                    }
`

**Comment by c-schuler** [comment]
Resolved: https://github.com/DBCG/cql_engine/commit/9400f36224a2b7c5b83c4bd250933ce69d7475d9
Get the 1.2.16-SNAPSHOT version of the engine for the fix.
Thank you =)
