### ISSUE TITLE
Let expression fails when assigning a query

### ISSUE THREAD

**Issue by jbyrdevans** [DBCG/cql_engine#208]
define "List 1":
    ({1, 2, 3}) i
        return i
        
define "List 2":
    ({4, 5, 6}) i
        return i

define "List of Lists":
    { "List 1", "List 2" }

define "Let Test Works":
    "List of Lists" IntegerList
        //let renamedIntegerList: (IntegerList i where 1 = 1)
        let renamedIntegerList: IntegerList
        return renamedIntegerList

define "Let Test Fails":
    "List of Lists" IntegerList
        let renamedIntegerList: (IntegerList i where 1 = 1)
        //let renamedIntegerList: IntegerList
        return renamedIntegerList

---------------
> Let Test Works [14:1] [[1, 2, 3], [4, 5, 6]]
> Let Test Fails [20:1] Could not resolve let expression reference 'renamedIntegerList' in library 'repro_let_tuple'.

**Comment by jreyno77** [comment]
Test Passing
