### ISSUE TITLE
Issue with Partial date/time values

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#21]
The following CQL:

    define HoursBetween: hours between @T06 and @T07:00:00Z

Will return an error:

    Error: ReadablePartial objects must have the same set of fields

But I believe this should return 1, because the precision is known in both date/time values at the level of precision of the comparison (hours).

**Comment by c-schuler** [comment]
Resolved here:
https://github.com/DBCG/cql_engine/commit/ccf49ce0f28c4052d91102697205c4509d82adb0
Fix is in the 1.2.20-SNAPSHOT.
