### ISSUE TITLE
Support general comparison for non-CQL types

### ISSUE THREAD

**Issue by umeshprasad123** [DBCG/cql_engine#215]
In CQL Engine 1.3.x  a FHIR type can not be compared. 
e.g. FHIR.dateTime
Work around for some FHIR type is to cast to system type e.g.  ToDate(value FHIR.date)
 
Enhancement should be added to support general comparison for non-CQL types.

**Comment by JPercival** [comment]
Support for non-CQL type comparison is now handled by the ModelResolver interface with the addition of `equals` and `equivalent`
