### ISSUE TITLE
Null Pointer Exception with Let operator in a query

### ISSUE THREAD

**Issue by jscherer-motivemi** [DBCG/cql_engine#218]
We are getting null pointer exceptions when we execute Let operator in a query. Below are two examples.

Example 1:
`define function ConditionsWithClaimsViaProvenance(conditions List<FHIR.Condition>, claims List<FHIR.Claim>): // returns List<FHIR.Condition>:
   from conditions Condition, claims Claim  
      let conditionProvenance: Condition.contained.Provenance, conditionProvenanceEntity: conditionProvenance.entity.what
    where exists ( conditionProvenanceEntity.reference ProvenanceReference
        where IsReferenced(Claim.id, ProvenanceReference)
    )return Condition`

Example 2:
`define "Encounters 60 Days Prior Through 60 Days After IPSD With Diagnosis of Depression":
    "Encounters 60 Days Prior Through 60 Days After IPSD" IPSDEncounter
        let IPSDCondition: IPSDEncounter.diagnosis.condition   
            with "Major Depression Diagnosis" MajorDepressionDiagnosis
                such that exists (
                    IPSDCondition.reference IPSDConditionReference
                        where EndsWith(IPSDConditionReference, MajorDepressionDiagnosis.id)
                )`

**Comment by JPercival** [comment]
Resolved by #220
