### ISSUE TITLE
From filter with 3 lists cannot resolve refernece to the 3rd item

### ISSUE THREAD

**Issue by jscherer-motivemi** [DBCG/cql_engine#219]
The _from_ filter shown below worked in CQL 1.2.57 and returns an error in CQL 1.3.10.
**Filter**
define "Dates of Well-Care Procedure Visits With PCP During First 15 Months of Life":
    from "Well-Care Procedures During First 15 Months of Life" WellCareProceduresDuringFirst15Months,
        "Primary Care Practitioners" PrimaryCarePractitioner,
        "Encounters During First 15 Months of Life" EncountersDuringFirst15Months
        where
        (
            exists (
                EncountersDuringFirst15Months.diagnosis.condition Condition
                    where EndsWith(Condition.reference, WellCareProceduresDuringFirst15Months.id)
            )
                and
                (
                    exists (
                        EncountersDuringFirst15Months.participant.individual Individual
                            where EndsWith(Individual.reference, PrimaryCarePractitioner.id)
                    )
                        or  exists (
                            WellCareProceduresDuringFirst15Months.performer.actor Performer
                                where EndsWith(Performer.reference, PrimaryCarePractitioner.id)
                        )
                )
        )
		return ToDate(WellCareProceduresDuringFirst15Months.performed."start")

**Error**: Could not resolve variable reference EncountersDuringFirst15Months

**Comment by JPercival** [comment]
Resolved by #220
