### ISSUE TITLE
Date/time Arithmetic fails adding durations?

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#22]
The following define:

    define Test3: E + 1 day

Fails with the error "Invalid duration day".

I also tried with the UCUM unit 'd', but it gives the same "Invalid duration" error.

**Comment by c-schuler** [comment]
Yes, this behavior is expected.

From the CQL spec:
+(left DateTime, right Quantity) DateTime
+(left Time, right Quantity) Time
Description:
The add (+) operator returns the value of the given date/time, incremented by the time-valued quantity, respecting variable length periods for calendar years and months. 
For DateTime values, the quantity unit must be one of:  **years, months, weeks, days, hours, minutes, seconds, or milliseconds.**
...

Change day to days and it will work...

**Comment by brynrhodes** [comment]
Good point, on a strict reading of the spec, those are the only allowed durations. The intent of that language though wasn't to restrict to only the plural varieties, but just to those specific time-valued granularities. I'll submit a comment to the spec to include the singular units, but I think the engine should be updated to allow for singular units as well.

**Comment by brynrhodes** [comment]
We should check other operations that take time-valued quantities as well to make sure we support both singular and plural precisions for all of them.

**Comment by c-schuler** [comment]
Resolved: https://github.com/DBCG/cql_engine/commit/b4fdf3aca128f2b4c964aeda0def6832d6190ad4

Pushed to 1.2.21-SNAPSHOT

**Comment by brynrhodes** [comment]
Submitted comment [1445](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1445)
