### ISSUE TITLE
Incomplete search parameter mapping in R4 data provider

### ISSUE THREAD

**Issue by c-schuler** [DBCG/cql_engine#241]
Whenever the patient compartment had multiple inclusion criteria for a resource, the R4 data provider returns null. 

Also, the STU3 data provider should be enhanced to include the complete set of mappings as well.

**Comment by JPercival** [comment]
There's now a a heuristic that searches the runtime definition of the resources for an appropriate search parameter.

https://github.com/DBCG/cql_engine/blob/master/cql-engine-fhir/src/main/java/org/opencds/cqf/cql/searchparam/SearchParameterResolver.java
