### ISSUE TITLE
Engine is failing on Equal(CodeableConcept, CodeableConcept) when grouping

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#25]
Running this library:

    using FHIR version '3.0.0'

    context Patient

    define ObservationCodes: 
        [Observation] O
            return O.code

    define LastNObservations:
        ObservationCodes C
             return { code: C, observations: ([Observation: code in C]).take(5) }

Using Patient-1136, gets the error:

>> Error: Cannot perform equal operator on types CodeableConcept and CodeableConcept

But CodeableConcept equality should be supported as a generic structure equality.

**Comment by c-schuler** [comment]
Should be resolved in the following [commit](https://github.com/DBCG/cql_engine/commit/462dd9072460a00cbd6e93250227e201e0d06524)

Published in 1.2.29-SNAPSHOT
