### ISSUE TITLE
The evaluation of TestRangeToInterval CQL function in TestFhirPath test class doesn't transform correctly

### ISSUE THREAD

**Issue by tsaferb** [DBCG/cql_engine#26]
If you try to print the evaluation of the result of this statement, context.resolveExpressionRef("TestRangeToInterval").getExpression().evaluate(context);
it would raise an exception because the the evaluation of the expression is null.
I think the culprit is the transformation doesn't set the value and the unit for the SimpleQuantity object being constructed in BaseFhirDataProvider class at line 265
  value = ((Quantity) value).castToSimpleQuantity(new SimpleQuantity());
In the castToSimpleQuantity(base obj), if the object being passed is SimpleQuantity it wouldn't set the values for value and unit.

**Comment by c-schuler** [comment]
I added a fix for this a few days back. Please review and close or explain why the fix is unsatisfactory. Thanks.
