### ISSUE TITLE
UriType issue

### ISSUE THREAD

**Issue by jbyrdevans** [DBCG/cql_engine#262]
toJavaPrimitive in the BaseDataProvider needs to add UriType mapping

**Comment by jbyrdevans** [comment]
// Should return a string, returns UriType[http://example.org/fhir/extensions/notDone]
define "test":
    ["DeviceUseStatement"] DU return (singleton from DU.extension).url

**Comment by jbyrdevans** [comment]
After correcting for the UriType issue, a new issue appeared:

define "Repro":
    [Condition] Condition
        where Condition.id.value = 'whatever'
> Invalid path: value for type: java.lang.String - this is likely an issue with the data model.

define "Repro 2":
    [Condition] Condition
        where Condition.id = 'whatever'
> Could not resolve call to operator 'ToString' in library 'FHIRHelpers'

**Comment by JPercival** [comment]
This has been fixed upstream in the latest translator snapshots.
