### ISSUE TITLE
Choice type argument not resolving to correct type

### ISSUE THREAD

**Issue by rob-reynolds** [DBCG/cql_engine#272]
Calling the following function with a value of type FHIR.Period results in the behavior of a FHIR.dateTime:
define function "Normalize Interval"(choice Choice<FHIR.dateTime, FHIR.Period>):
  if choice is FHIR.dateTime then
	  Interval[FHIRHelpers.ToDateTime(choice as FHIR.dateTime), FHIRHelpers.ToDateTime(choice as FHIR.dateTime)]
	else
	  FHIRHelpers.ToInterval(choice as FHIR.Period)

Furthermore, changing the order of the choice types results in the behavior of a FHIR.Period:
choice Choice<FHIR.Period, FHIR.dateTime>

Repro:
Connectathon/master commit e93aeada80b89da54f7f56462a41c35fc0b859b8, fhir4/130R4 numerator test, using "Normalize Interval" from MATGlobalCommonFunctions_FHIR4-4.0.000

**Comment by JPercival** [comment]
Bug in the CQL translator. Resolved in versions 1.3.19 ad 1.4.8.
