### ISSUE TITLE
Expression cache is not being cleared on context change

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#273]
A change to the context should clear the expression cache.

**Comment by JPercival** [comment]
Issue was in downstream project. Misuse of Context. Resolved by https://github.com/DBCG/cqf-ruler/issues/153

**Comment by JPercival** [comment]
Discussed with Bryn offline and got more details. This functionality is needed to support the next version of CQL with related-context retrieves

**Comment by JPercival** [comment]
Resolved by #497
