### ISSUE TITLE
Report the same location context info for errors as for successes

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_engine#28]
When a CQL named expression is evaluated successfully, the output gives the expression name and line number in the source code, for example:

```
>> Is Colonoscopy In Last Ten Years [304:1] false
```

However, when there are runtime errors with an expression, that context is not indicated, for example:

```
>> Error: HTTP 404 Not Found
```

The task of this ticket is to update the engine such that the expression name / line number context is always reported regardless of whether the evaluation result is successful or an error.

This information is important for tracking down where in many possible places the error may originate in the source code.

**Comment by c-schuler** [comment]
This is actually not an engine issue. Please close and re-raise in the CQL Runner. Thanks.

**Comment by duncand** [comment]
Okay, issue https://github.com/DBCG/cql_runner/issues/20 replaces the current one, closing.
