### ISSUE TITLE
Non-patient Context Support

### ISSUE THREAD

**Issue by c-schuler** [DBCG/cql_engine#293]
Add the ability to reference non-patient context and rename the "Population" context to "Unconstrained".

Taken from [STU comment 1716](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1716):

- Available contexts will be defined by the model
- Relationships of context to types in the model will be represented in the model
- Models SHALL define at least one context named Unfiltered that means no specific context
- Default is Unfiltered (rather than Patient)

**Comment by JPercival** [comment]
Resolved by various refactoring PRs the ModelResolvers to get context information dynamically.
