### ISSUE TITLE
Implement ConvertQuantity Operation

### ISSUE THREAD

**Issue by c-schuler** [DBCG/cql_engine#298]
From https://cql.hl7.org/09-b-cqlreference.html#convertquantity:

```
convert <quantity> to <unit>
ConvertQuantity(argument Quantity, unit String)
```

The ConvertQuantity operator converts a Quantity to an equivalent Quantity with the given unit. If the unit of the input quantity can be converted to the target unit, the result is an equivalent Quantity with the target unit. Otherwise, the result is null.

Note that implementations are not required to support quantity conversion. Implementations that do support unit conversion shall do so according to the conversion specified by UCUM. Implementations that do not support unit conversion shall throw an error if an unsupported unit conversion is requested with this operation.

If either argument is null, the result is null.

```
define ConvertQuantity: ConvertQuantity(5 'mg', 'g')
define ConvertSyntax: convert 5 'mg' to 'g'
```

**Comment by JPercival** [comment]
Resolved with #324
