### ISSUE TITLE
Setting com.sun.xml.internal.bind.ObjectFactory property raises an exception on JRE server

### ISSUE THREAD

**Issue by tsaferb** [DBCG/cql_engine#30]
This code u.setProperty("com.sun.xml.internal.bind.ObjectFactory", new ObjectFactoryEx() raises an exception when the engine is run in JRE server environment. The issue is related to 			https://bugs.eclipse.org/bugs/show_bug.cgi?id=406032
and https://javaee.github.io/jaxb-v2/doc/user-guide/ch03.html#compiling-xml-schema-adding-behaviors.

**Comment by tsaferb** [comment]
Yes, I checked in a fix for it. Interesting how I didn't catch it. Thanks

**Comment by c-schuler** [comment]
Please verify that the applied fix in the referenced commit resolves this issue and close. Thanks
