### ISSUE TITLE
Difference in weeks produce wrong result

### ISSUE THREAD

**Issue by mdnazmulkarim** [DBCG/cql_engine#300]
difference in weeks between @2012-03-10T22:05:09 and @2012-03-24T07:19:33
should produce 1 but we get 2 instead.

**Comment by brynrhodes** [comment]
As @c-schuler points out, the spec actually considers Sunday the starting point for the purposes of determining boundary crossing with weeks:

https://cql.hl7.org/02-authorsguide.html#computing-durations-and-differences
https://cql.hl7.org/09-b-cqlreference.html#difference

**Comment by c-schuler** [comment]
To give a bit more detail: `@2012-03-10T22:05:09` is a Sunday (the beginning of the week) and `@2012-03-24T07:19:33` is also a Sunday. Meaning the Sunday boundary was crossed twice, which results in a difference of 2 weeks.

**Comment by mdnazmulkarim** [comment]
Thanks for your nice clarification. Just checking my understanding is right: In that way, @2012-03-09T22:05:09 and @2012-03-25T07:19:33  should result in 3 as 3 Sunday crossed by.

**Comment by JPercival** [comment]
Resolved by #332
