### ISSUE TITLE
NullPointerException for some expression while evaluate

### ISSUE THREAD

**Issue by mdnazmulkarim** [DBCG/cql_engine#304]
Tests are in CqlListOperatorsTest.
Expression: { 'a', 'b', null } contains null 
Expression: null contains 'a'
Expression : Exists({ null })
Expression : null in { 1, null }
Expression : {'s', 'a', 'm'} includes null
Expression : null included in {2}

**Comment by mdnazmulkarim** [comment]
These issues are resolved in current developed.

**Comment by JPercival** [comment]
Resolved by #332
