### ISSUE TITLE
Error when evaluating on or after

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#31]
The following script:

    define TestDateTime1: @2017-12-20T11:00:00
    define TestDateTime2: @2017-12-20T11:00:00
    define Test: TestDateTime1 on or after TestDateTime2

Gives the error "Precision must be specified". However, the SameOrAfter operator in ELM does not require precision (the precision attribute is optional). In addition, the CQL specification in section 2.5.4.2 indicates:

> If no precision is specified, these operators are equivalent to the symbolic comparison operators, implying comparison precision to the millisecond. 

The engine should be updated to use "millisecond" precision if no precision is specified for the SameOrAfter operator, as well as any other operators that require precision.

**Comment by c-schuler** [comment]
Resolution of this issue in the following [commit](https://github.com/DBCG/cql_engine/commit/0c0fe5bf13db6333c38821a35a4234b9c0d980ac)

**Comment by brynrhodes** [comment]
Perfect, thanks!
