### ISSUE TITLE
About running project and how to convert from CQL to ELM file.

### ISSUE THREAD

**Issue by shardulbanker** [DBCG/cql_engine#337]
How to run this project? How can I give any CQL file as input and convert into ELM file?

**Comment by brynrhodes** [comment]
Apologies for missing this, the engine runs ELM, it does not translate, for that you use the CQL-to-ELM translator:
https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/OVERVIEW.md

**Comment by JPercival** [comment]
Closing as the question was answered. Feel free to reopen if needed.
