### ISSUE TITLE
Minimum Integer value -2147483648 can not be selected as a literal

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_engine#36]
The the minimum Integer value -2147483648 can not be selected as a literal.

Run the following CQL:

```
define x: minimum Integer
define y: -2147483648
```

Expected result:

```
x: -2147483648
y: -2147483648
```

Actual result:

```
x: -2147483648
y: java.lang.NumberFormatException: For input string: "2147483648"
```

These failing CQL Engine tests reflect this bug:

- CqlArithmeticFunctionsTest -> IntegerMinValue

The root of the problem is that the Translator parses -2147483648
not as a single literal but rather as a Negate operator call paired
with a positive Integer literal, and then the CQL Engine has a runtime
numeric overflow exception trying to parse the ELM in question.

```
      <def name="y" context="Population" accessLevel="Public">
         <expression xsi:type="Negate">
            <operand valueType="t:Integer" value="2147483648" xsi:type="Literal"/>
         </expression>
      </def>
```

The proper fix for this would be in the Translator.

A kludge fix for this would be in the Engine that special cases any
occurrances in input ELM of a "Negate" operator call paired with a numeric literal
such that it factors them into a negated literal before converting to a number.

**Comment by c-schuler** [comment]
Fixed in #87
