### ISSUE TITLE
cql-engine-fhir FhirModelResolver Overloaded Constructors

### ISSUE THREAD

**Issue by blangley28** [DBCG/cql_engine#360]
The FhirModelResolvers in cql-engine-fhir always create a new fhir context. This is an expensive call which applications are encouraged to only perform once. These model resolvers contain an overloaded constructor which accepts a fhir context but they are private.

I suggest these overloaded constructors are made public so they can be used. At first I thought perhaps they were private to ensure the correct fhir version is used for the context, but the classes actually validate they are the correct version. As such I don't think it would be an issue to make these overloaded constructors public so a fhir context object can be passed in.

**Comment by JPercival** [comment]
Hi @blangley28 . The constructors are private because the FhirContexts are initialized in a particular way to cover a few gaps in the base HAPI structures. IOW, you can't pass in any ole FhirContext you created elsewhere. However, if you'd like to reuse the context that's initialized the FhirModelResolved exposes getFhirContext(). You can also cache the FhirModelResolver by FhirVersion if needed.

**Comment by blangley28** [comment]
@JPercival that makes sense but could you please clarify about the FhirContexts? I took the R4FhirModelResolver file and modified it myself passing in my `FhirContext.forR4()`. I'm new to this whole thing - are there other ways to initialize FhirContexts (in this case lets only consider for R4) other than the `ca.uhn.fhir.context.FhirContext.forR4` method? It seems to be working fine for me passing in my own FhirContext which was created in this way

**Comment by JPercival** [comment]
Once the FhirContext is "initialized" you can no longer add custom types. Merely creating the context isn't enough to trigger initialization. You actually have to access and use the context in some way to cause that to happen.

Here's where the custom types are registered:

https://github.com/jamesagnew/hapi-fhir/blob/0c008e11be676b9b43c79b8e7659f506c0fac0ef/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirContext.java#L750

Here's where they are scanned (as part of "initialization"):

https://github.com/jamesagnew/hapi-fhir/blob/0c008e11be676b9b43c79b8e7659f506c0fac0ef/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirContext.java#L779

Later on in that same function "initialized" is set to true, and new custom types won't be picked up:

https://github.com/jamesagnew/hapi-fhir/blob/0c008e11be676b9b43c79b8e7659f506c0fac0ef/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirContext.java#L828

This is checked in the validateInitialized() function:

https://github.com/jamesagnew/hapi-fhir/blob/0c008e11be676b9b43c79b8e7659f506c0fac0ef/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirContext.java#L890

And many different context actions trigger that call.

So, if you create a brand new context and pass it in without doing anything else with it, it will technically work. But if you have a context you've actually used in pretty much any other way, it won't. Given any sort of shared context would almost certainly have been used by some other logic and would already be initialized, it didn't make sense to allow one to be passed in. Rather, the ModelResolver adds the custom types and then that context can be shared once it's initialized with the custom types.

**Comment by JPercival** [comment]
Closed because I provided an explanation. Feel free to reopen if needed!
