### ISSUE TITLE
Support Modular Arithmetic for Quantities

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#372]
Support the new Quantity overloads of div and mod:
https://cql.hl7.org/2020May/09-b-cqlreference.html#modulo
https://cql.hl7.org/2020May/09-b-cqlreference.html#truncated-divide

**Comment by mdnazmulkarim** [comment]
https://github.com/DBCG/cql_engine/pull/495

**Comment by mdnazmulkarim** [comment]
Closing the issue based on PR https://github.com/DBCG/cql_engine/pull/495 is merged.
