### ISSUE TITLE
Support System.Long type

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#376]
CQL 1.5 added support for the System.Long type (64-bit integer):
https://cql.hl7.org/2020May/09-b-cqlreference.html#long-1

Also add support for all the operators for long:
+, -, *, /, div, mod, ToLong, ConvertsToLong, ConvertsToInteger, ConvertsToString, ToString, Between, >, <, =, ~, !=, !~, <=, >=, Abs, Exp, Log, Ln, Maximum, Minimum, Negate, Predecessor, Successor, Power, Max, Min, Product, Sum,

**Comment by duncand** [comment]
I have a question.  Rather than the dual of Integer and Long in the CQL Engine, wouldn't it be simpler to just use the Java Long to implement all integer types?  All modern hardware of concern has been natively 64 bit for a solid 15 years now.  (Copy of this on both the issue and the pull request.)

**Comment by JPercival** [comment]
Resolved by #491
