### ISSUE TITLE
Parameters not passed to CQL

### ISSUE THREAD

**Issue by csandersdev** [DBCG/cql_engine#406]
Using the latest from the develop branch. When I create a simple library that uses parameters, the parameters are not passed into the execution engine. See attached test patch replication details. 
[test2-patch.txt](https://github.com/DBCG/cql_engine/files/5307162/test2-patch.txt)

I believe this is a simple enough thing to patch in the CqlEngine code by adding a loop that passes parameters into the current library before the check for included libraries. See attached fix proposal. I'm happy to PR this if you agree.
[fix2-patch.txt](https://github.com/DBCG/cql_engine/files/5307175/fix2-patch.txt)

**Comment by JPercival** [comment]
Hi @csandersdev 

Thanks for the repro and code. Looks right to me. Want to submit a PR?

**Comment by csandersdev** [comment]
Thanks, @JPercival. [PR 408](https://github.com/DBCG/cql_engine/pull/408) submitted.

**Comment by JPercival** [comment]
Resolved by #408
