### ISSUE TITLE
Translation fails on uncertainty-resulting days-between

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_engine#41]
The Translator fails to translate an uncertainty.

Run the following CQL:

```
define x: days between DateTime(2015, 2, 10) and DateTime(2015, 3)
define y: Interval [ 19, 49 ]
define z: Equivalent(x,y)
```

Expected result:

```
x: Interval [ 19, 49 ]
y: Interval [ 19, 49 ]
z: true
```

Actual result:

```
x: Interval [ 19, 49 ]
y: Interval [ 19, 49 ]
z: Could not resolve call to operator Equivalent with signature (System.Integer,interval<System.Integer>).
```

These failing CQL Engine tests reflect this bug:

- CqlTypesTest.xml -> DateTimeUncertain

**Comment by duncand** [comment]
These additional failing CQL Engine tests reflect this bug:

* CqlDateTimeOperatorsTest.xml -> DateTimeDurationBetweenUncertainInterval
* CqlDateTimeOperatorsTest.xml -> DateTimeDurationBetweenUncertainInterval2
* CqlDateTimeOperatorsTest.xml -> DateTimeDurationBetweenUncertainAdd
* CqlDateTimeOperatorsTest.xml -> DateTimeDurationBetweenUncertainSubtract
* CqlDateTimeOperatorsTest.xml -> DateTimeDurationBetweenUncertainMultiply

**Comment by JPercival** [comment]
Closing, as this is actually a translator issue.
