### ISSUE TITLE
MessageEvaluator::stripPHI is unimplemented

### ISSUE THREAD

**Issue by deekim** [DBCG/cql_engine#415]
Hi :)

I was going through some of the `todo`s in the codebase and saw that `MessageEvaluator::stripPHI` was not implemented.

[MessageEvaluator.java](https://github.com/DBCG/cql_engine/blob/v1.5.0/engine/src/main/java/org/opencds/cqf/cql/engine/elm/execution/MessageEvaluator.java#L50-L53)
```java
private static Object stripPHI(Object source) {
    // TODO
    return source;
}
```

I have some ideas on how one might implement this functionality but was curious if the maintainers had discussed this topic at all.

**Comment by brynrhodes** [comment]
Hi @deekim , we have discussed it, but don't have any concrete plans at the moment, would certainly welcome any input from the community!

**Comment by deekim** [comment]
Gotcha. Well, my first thought was to provide a `PHIObfuscator` contract:
```java
IPHIObfuscator obfuscator = new DefaultPHIObfuscator();

...

private static String stripPHI(Object source) {
  return obfuscator.obfuscate(source);
}
```

```java
public class DefaultPHIObfuscator implements IPHIObfuscator {
...
public String obfuscate(Object source) {
  // do some class checks or the like to see if it's "safe" to return fields
  // such as an Interval object?

  // or have some marker annotations on class or fields?
  // e.g. @NonPHI or @PHI
  // todo: how to handle nested objects?
  
  // else return "something meaningful indicating PHI masking?"
}
```

I'm still formulating the most meaningful way to implement `DefaultPHIObfuscator`,
but I can open up a Draft PR for something like this if that makes sense to you @brynrhodes?

**Comment by brynrhodes** [comment]
Yes, this makes sense as an interface, and a simple way to plug it in to the current architecture might be to ask the data provider for an obfuscator? @JPercival, any objection to adding a `getObfuscator()` method to the dataProvider interface?

**Comment by deekim** [comment]
That would indeed be simpler... 😄 
I'm still new to using the library, so I ended up using [google/guice](https://github.com/google/guice/) `CDI` to inject the implementation. But I can definitely change things to just add it to `dataProvider` if that was the role of that interface.

**Comment by deekim** [comment]
Sorry to bug you again, @JPercival. 
I just wanted to check-in to see if you had an opinion on using `DataProvider` vs. dependency injection?
Here's a _WIP_ of what I was thinking: https://github.com/DBCG/cql_engine/compare/master...deekim:message-evaluator-phi-strip

**Comment by deekim** [comment]
No worries!

I can make that change and open up a PR. Thanks for the explanation.
I'll have to do a bit more research into the `cql-evaluator` project on my part since I was unaware of its existence 😛
