### ISSUE TITLE
Add Code Coverage to the Build

### ISSUE THREAD

**Issue by JPercival** [DBCG/cql_engine#425]
There are quite a few tests in the cql-engine project but there's not currently any code coverage analysis. We should add that to the build and add requirements that new code has X% coverage for merging.

**Comment by deekim** [comment]
I think this is a great idea.
Let me know if you'd like any help setting this (or #426 and #427) up.
Would be happy to help out 😄

**Comment by JPercival** [comment]
All contributions welcome! Unfortunately, none of these are currently very high on my backlog due to other requests. :)

**Comment by JPercival** [comment]
Resolved by #433
