### ISSUE TITLE
Maven compiler error when running under JDK8

### ISSUE THREAD

**Issue by dkwasny-ibm** [DBCG/cql_engine#430]
I'm hitting the following error when attempting to run a maven build on my machine using JDK8.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project engine: Fatal error compiling: invalid flag: --release -> [Help 1]
```
This seems to be caused by the use of `<release>8</release>` within the configuration for the compiler plugin, which only works for JDK9+.

Commenting out that line fixes the build error for me, but I'm not sure if that's the right way to go.
I found a [post on StackOverflow](https://stackoverflow.com/a/43103038) mentioning that the `<release>` feature adds a bit more safety to the compilation over just specifying `<source>` and `<target>`.

I should probably just finally upgrade my JDK to 11, but I figure officially stating the desired compiler version will help any future devs who are still on JDK8.

**Comment by deekim** [comment]
`@JPercival` gave a bit more context in #418 as a _fyi_.

> So, at one point we upgraded to 11 to get to the latest LTS release and then discovered many of the institutions we were deploying at only supported 8. So we had to downgrade. Looks like it was never caught on the .travis.yml file.

**Comment by JPercival** [comment]
I think the path here is what @deekim suggested in #418. Add a build matrix for 8 and 11, and update the maven pom.xml to have slightly different configuration for the compiler plugin with profiles for 8 and 11. 8 would omit that tag, and 11 would include it.
