### ISSUE TITLE
Checking if String is in a ValueSet executes a potentially incomplete request

### ISSUE THREAD

**Issue by dkwasny-ibm** [DBCG/cql_engine#437]
Disclaimer: I'm developing against the IBM FHIR server, which does behave differently than the HAPI FHIR server (detailed below).

I'm attempting to write a simple CQL based on the [Terminology](https://cql.hl7.org/02-authorsguide.html#terminology) documentation found in the CQL docs.
In particular, I'm having issues with the following `valueset` and `define` statement:
```
valueset "Female Administrative Sex": 'test-value-set'
...
define PatientIsFemale: Patient.gender in "Female Administrative Sex"
```
This `define` eventually executes the following request:
```
https://localhost:9443/fhir-server/api/v4/ValueSet/test-value-set/$validate-code?code=female
```

Our FHIR server responds with an error stating that the `system` parameter was not present.
Looking at the [validate-code](https://www.hl7.org/fhir/operation-valueset-validate-code.html) docs, it says "if a code is provided, a system or a context must be provided".
Adding the expected codesystem to the above request produces the correct result.

It looks like the HAPI FHIR server returns a valid, but questionable, result when a `validate-code` request is sent with a `code` but no `system`.
Here's two example URLs for reference:
```
http://hapi.fhir.org/baseR4/ValueSet/sact-treatment-intent-code/$validate-code?code=373846009
http://hapi.fhir.org/baseR4/ValueSet/sact-treatment-intent-code/$validate-code?code=373846009&system=http://snomed.info/sct
```

We were able to get the CQL to run correctly by explicitly stating the code system as such:
```
define PatientIsFemale: System.Code {code: Patient.gender, system: 'http://hl7.org/fhir/v3/AdministrativeGender'} in "Female Administrative Sex"
```

The code at [InValueSetEvaluator#48](https://github.com/DBCG/cql_engine/blob/41d9bee33aca7a7756010184c3ca5cde7b159355/engine/src/main/java/org/opencds/cqf/cql/engine/elm/execution/InValueSetEvaluator.java#L48) and [R4FhirTerminologyProvider#L65](https://github.com/DBCG/cql_engine/blob/41d9bee33aca7a7756010184c3ca5cde7b159355/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/terminology/R4FhirTerminologyProvider.java#L65) tells me that "checking if a string is in a valueset" is a valid usecase.

Is there something I'm missing here?  With my limited knowledge of FHIR and CQL, I can't see how we can check if a plain string is in a valueset without having a codeset attached to it (i.e. a `Code`).

EDIT: Updated HAPI example links.  Looks like my original valueset choice was removed.

**Comment by JPercival** [comment]
The spec for [validate-code](https://www.hl7.org/fhir/operation-valueset-validate-code.html) marks system as optional buy says the following:

> The code that is to be validated. If a code is provided, a system or a context must be provided (if a context is provided, then the server SHALL ensure that the code is not ambiguous without a system)

Based on how I interpret that I'd say this is a bug in the engine (and in HAPI). @brynrhodes ?
