### ISSUE TITLE
Interval intersect with null throws java null pointer exception

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_engine#44]
Try to run this CQL:

```
define x: Interval[1, 10] intersect Interval[5, null)
```

Expected result is null, but actual result is the CQL Engine dies with a java.lang.NullPointerException.

This bug is demonstrated in a CQL Engine test failure of CqlIntervalOperatorsTest.xml -> TestIntersectNull.

**Comment by duncand** [comment]
I consider pull request #82 in particular and also possibly #80 to block any attempt to fix issue #44, as they might have the same cause; or, if the cause is different, the fix probably involves the same area of the code.  When the above 2 pull requests are merged, then #44 would be un-blocked.

**Comment by JPercival** [comment]
Resolved by #80
