### ISSUE TITLE
How to define an external function returning a Tuple in CQL

### ISSUE THREAD

**Issue by dmartino88** [DBCG/cql_engine#457]
I need to define and invoke an external function returning a Tuple object. How it is possible?
I try several solutions but I have syntax errors.
For example

**library ExamplePatientView version '0.0.1'
using FHIR version '4.0.0'
include FHIRHelpers version '4.0.0' called FHIRHelpers
define function MyCustomFunction() returns Tuple : external
context Patient
define myfunction: MyCustomFunction()**

Another solution that I tried was defining a new parameter tuple likes this:

**library ExamplePatientView version '0.0.1'
using FHIR version '4.0.0'
include FHIRHelpers version '4.0.0' called FHIRHelpers
parameter Info Tuple { city String, address String }
define function MyCustomFunction() returns Info : external
context Patient
define myfunction: MyCustomFunction()**

The validator gives me always syntax errors. 
How Can solve my problem? I want to define an external function returning a Tuple where I know how the tuple consists of.

**Comment by dmartino88** [comment]
The engine does not recognize syntax Tuple<Info>

**library ExamplePatientView version '0.0.1'
using FHIR version '4.0.0'
include FHIRHelpers version '4.0.0' called FHIRHelpers
parameter Info Tuple { city String, address String }
define function MyCustomFunction() returns Tuple<Info> : external
context Patient
define myfunction: MyCustomFunction()**

**Comment by JPercival** [comment]
Hi @dmartino88!

The `Tuple` definition requires braces to specify the elements, as you've done for:

`parameter Info Tuple { city String, address String }`

The parameter definition above has `Info` as the Parameter name, and `Tuple { city String, address String }` as the parameter type. This allows you to pass external parameters to CQL. It's not a declaration of a named Tuple type. If you want to use the same type of Tuple as the return value of the external function you have to fully specify the Tuple type again. Here's an example:

```cql
library ExamplePatientView version '0.0.1'
using FHIR version '4.0.0' 
include FHIRHelpers version '4.0.0' called FHIRHelpers 

parameter Info Tuple { city String, address String } 

define function MyCustomFunction() returns Tuple { city String, address String } : external

define function MyFunction():
  MyCustomFunction()
  ```

**Comment by dmartino88** [comment]
Hi @JPercival,
thank you very much. I solved my problem following your response.

**Comment by dmartino88** [comment]
Hi @JPercival,
is it also possible to define an external function returning a Tuple of Tuple object?

Something like 

`
define function MyCustomFunction() returns Tuple { myAttribute Tuple } : external
`
without specifying the nested Tuple type again.
