### ISSUE TITLE
R4FhirTerminologyProvider silently ignores a missing ValueSet

### ISSUE THREAD

**Issue by csandersdev** [DBCG/cql_engine#459]
When the user executes a CQL that links to a ValueSet that does not exist in the target FHIR server, the R4FhirTerminologyProvider will mask the error and treat this as a ValueSet with 0 codes. See [here](https://github.com/DBCG/cql_engine/blob/master/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/terminology/R4FhirTerminologyProvider.java#L79-L81) for an example, but the behavior is consistent for each of the in, expand, and lookup methods. Our expectation is that an error should be thrown if a ValueSet resource does not exist.

**Comment by JPercival** [comment]
Resolved by #462
