### ISSUE TITLE
R4FhirTerminologyProvoider ignores ValueSet.version and ValueSet.codeSystems when resolving the resource

### ISSUE THREAD

**Issue by csandersdev** [DBCG/cql_engine#461]
The resolveByUrl method in R4FhirTerminologyProvider will lookup a ValueSet resource based on the ValueSet.id field, ignoring the ValueSet.version and ValueSet.codeSystems properties. The [CQL author's guide](https://cql.hl7.org/02-authorsguide.html#valuesets) calls out behavior for the version and codesystems fields that should be provided in the implementation.

**Comment by csandersdev** [comment]
In order to completely resolve this issue, the RetrieveEvaluator will need to be updated to populate the version and codesystems information [in the ValueSetInfo that is created](https://github.com/DBCG/cql_engine/blob/8a11ef270d9f54b74d9996441ce76572fe1374ef/engine/src/main/java/org/opencds/cqf/cql/engine/elm/execution/RetrieveEvaluator.java#L28) and then pass that complete ValueSetInfo object to the RetrieveProvider. Right now, the RetrieveProvider interface only accepts ValueSet ID as a string. If ``RestFhirRetrieveProvider.isExpandValueSets() == true``, the retrieve provider will [reconstruct a ValueSetInfo with just the ID](https://github.com/DBCG/cql_engine/blob/8a11ef270d9f54b74d9996441ce76572fe1374ef/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/retrieve/SearchParamFhirRetrieveProvider.java#L160) and call ``TerminologyProvider.expand()`` to get the list of codes. The terminology provider doesn't even have the version and codesystem information available if it wanted to make a decision based on those values.

**Comment by JPercival** [comment]
Resolved by #462
