### ISSUE TITLE
Query building for code:in not working

### ISSUE THREAD

**Issue by csandersdev** [DBCG/cql_engine#466]
The IBM FHIR server that I use added support for the token :in modifier in [version 4.7.0](https://github.com/IBM/FHIR/releases/tag/4.7.0). The RestFhirRetrieveProvider that is provided in the engine.fhir project has a mode that will leverage the :in modifier when doing filtered retrieves (e.g. [Condition: MyValueSet]). I've been trying to get that feature to work with an IBM FHIR 4.7.0 instance, but the queries that are being generated are not correct. The :in modifier is not being appended to the query parameter name. As best as I can tell, this is an issue with HAPI client library.  The [code in question](https://github.com/DBCG/cql_engine/blob/48c95b816724f2558ef7516cd6fb6494787e7aa6/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/retrieve/SearchParamFhirRetrieveProvider.java#L163) ends up looking something like this at runtime...

```java
client.search().forResource(Condition.class).where(
				Collections.singletonMap(Condition.SP_CODE, 
						Collections.singletonList(
								new TokenParam("/ValueSet/1.2.3.4")
									.setModifier(TokenParamModifier.IN)))).execute();
```

...and the query that is being generated in by the HAPI client is....

```
[main] INFO ca.uhn.fhir.rest.client.interceptor.LoggingInterceptor - Client request: GET http://hapi.fhir.org/baseR4/Condition?code=http%3A%2F%2Fcts.nlm.nih.gov%2Ffhir%2FValueSet%2F1.2.3.4 HTTP/1.1
```

I posted a [question](https://groups.google.com/g/hapi-fhir/c/oLGhNgPjbjU) to the HAPI FHIR Google Group seeking guidance on this topic and am waiting on a response. I will update this ticket as I learn more.

I know that there is the ``TerminologyAwareRetrieveProvider.setExpandValueSets(true)`` feature. It is important to note, however, that the [default value for that flag](https://github.com/DBCG/cql_engine/blob/48c95b816724f2558ef7516cd6fb6494787e7aa6/engine/src/main/java/org/opencds/cqf/cql/engine/retrieve/TerminologyAwareRetrieveProvider.java#L13) is false right now, so the engine will try to use the :in modifier unless the user explicitly enables pre-expansion via the TerminologyProvider. I am leveraging that flag for pre-4.7.0 IBM FHIR, but I was hoping to use the ":in" modifier to reduce the number of REST calls to the server now that support is available.

**Comment by csandersdev** [comment]
I was fairly certain that this used to work, so I've been digging around trying to find when it stopped working. I believe it was the change in RestFhirRetrieveProvider to switch from the ``byUrl(toNormalizedQueryString(ctx))`` implementation to the version that uses the HAPI IQueryParameterType map. See [this change](https://github.com/DBCG/cql_engine/commit/feaeabf9c1ca73a50c0d1592d680990ef4df961c#diff-3e49d67c89b44f9788f6d808a9a9247678c186307666dec6200e0453de8893f1L71-L73). @JPercival can you elaborate on why that change was needed? Using the HAPI query parameter builder definitely seems like a positive overall change if it worked, but was there a specific bug that was being addressed at the same time?

**Comment by JPercival** [comment]
Yes, there was a case where the `toNormalizedQueryString` was dropping search parameters. I'll take a look and see if I can find why this is failing.

**Comment by JPercival** [comment]
This is actually hapifhir/hapi-fhir#2426, which is resolved in HAPI 5.4. This gist of it is that parameter modifiers are not serialized correctly. The engine will update to 5.4 shortly after release which is scheduled for May 20, as I understand it.

**Comment by csandersdev** [comment]
Thanks. I missed that when looking for details. FYI, there is a [unit test](https://github.com/DBCG/cql_engine/blob/ee5ad2ff0e78b797399617d4acd94d90046a4051/engine.fhir/src/test/java/org/opencds/cqf/cql/engine/fhir/retrieve/TestRestFhirRetrieveProvider.java#L78) for the retrieve provider that I added to verify page size was being properly sent to the FHIR server that will start failing whenever this starts working.

**Comment by JPercival** [comment]
Thanks for the heads up. I'll revisit and update the test once 5.4 is released and we update.
