### ISSUE TITLE
SLF4J logging in tests is broken

### ISSUE THREAD

**Issue by csandersdev** [DBCG/cql_engine#469]
The SLF4J logging specifically for tests was broken by [this commit](https://github.com/DBCG/cql_engine/commit/e939ec863b580163c07856e2f85e1b11bd0f07ca) as part of a maintenance script execution. The reason it is broken is because the engine inherits slf4j-api version 1.7.X from the translator and the slf4j-simple log binding is now set to version 2.X. SLF4J's log binding mechanism changed between version 1.X and 2.X, so you need to be using API 2.X when you are using a 2.X log binding as described [here](http://www.slf4j.org/codes.html#StaticLoggerBinder). The engine should declare a version of the SLF4J API and make sure the version of the slf4j-simple log binding matches what API is being used. It is an easy enough change, but I would like some input from the project owners on whether or not 2.0.0-alpha1 was an intentional change or should the engine be using the stable 1.7.X lineage. I personally lean towards 1.7.X because it 2.X is still alpha and 1.7.X is most likely to be used in consuming applications at this time.

**Comment by JPercival** [comment]
1.7.X. Will have to exclude it from the script.

**Comment by JPercival** [comment]
Resolved by #470
