### ISSUE TITLE
Can the keyword "let" be used inside a function?

### ISSUE THREAD

**Issue by dmartino88** [DBCG/cql_engine#476]
I need a function that returns a Tuple when specific conditions have satisfied, to do this I used keywork "let" but I have syntax errors at let word.

Following a piece of code that I am writing

```
define function myCard(myObsCode String, myCompCode String, myValue Decimal) returns Tuple {extension String, title String, description String}:
let 
    myObs: singleton from ([Observation] O where O.code[0].coding[0].code = myObsCode )
    myComponent: singleton from (myObs.component C where C.code[0].coding[0].code = myCompCode )
return (
    case
           when myValue > (myComponent.value as Quantity).value
                 then Tuple {extension: info, title: title, description: mydescription}
            when myValue < (myComponent.value as Quantity).value
                 then Tuple {extension: info, title: title, description: mydescription}
            else null
    end
)
    
```

My function should return a Tuple when it exists an Observation with a specific code, that has the specific component.code where the value of such component is for example greater/less than the value that I pass to the function. 

**I have a syntax error to the keyword "let"**, why? **Can I use the keyword "let" in a function?** @JPercival

**Comment by JPercival** [comment]
I apologize for the delay. The "let" clause can be used inside a function but only within the context of a query. Here's the relevant specification:

https://cql.hl7.org/03-developersguide.html#queries-1

And here's a trivial example that doesn't really do anything:

```cql
define function example():
  [Medication] M
    let status: (M.status)
    return status
```

**Comment by dmartino88** [comment]
Thank you very much for your reply. **Why does the cql_engine give syntax error at "let" in the code that I shared?** Is it possible to define a function that starting from a list of  FHIR resources (e.g. list of Observation) returns a list of Tuple as I stated in my question?

**Comment by JPercival** [comment]
Sorry, I wasn't clear. Your code is not syntactically valid because **the let clause is not inside of a query context**.

In CQL queries take the form:

```
<source> <identifier>
                <let>?
                <join>*
                <where>?
                (<return> | <aggregate>)?
                <sort>?
```

Here's the format syntax specification: https://cql.hl7.org/08-a-cqlsyntax.html
And the spec for queries: https://cql.hl7.org/02-authorsguide.html#queries

You need to rewrite your function in terms of a query to use let. Something along the lines of:

```
define function myCard(myObsCode String, myCompCode String, myValue Decimal, info String, title String, mydescription String) returns Tuple {extension String, title String, description String}:
    singleton from ([Observation] O
     let myComponent: O.component
     where O.code.coding[0].code = myObsCode 
     and myComponent.code[0].coding[0].code = myCompCode
     return  
      case
             when myValue > myComponent.value[0]
                   then Tuple {extension: info, title: title, description: mydescription}
              when myValue < myComponent.value[0]
                   then Tuple {extension: info, title: title, description: mydescription}
              else null
      end)
```

**Comment by dmartino88** [comment]
Thank you, I changed my code according to the cql syntax.
