### ISSUE TITLE
Which release version to use for R4 support?

### ISSUE THREAD

**Issue by kcook22** [DBCG/cql_engine#477]
We are trying to set up the cql engine and execution service to execute against an R4 HAPI FHIR server. We are using 1.3.10-SNAPSHOT release of the cql_engine. 

In the CQL code, we have "using FHIR version '4.0.0'" , but our response seems to return an STU3 bundle: "resultType": "FhirBundleCursorStu3". Any help would be much appreciated, thanks!

**Comment by JPercival** [comment]
Hmm.. Likely a bug in 1.3.10-SNAPSHOT.

The engine release 1.5.1 is backwards compatible with CQL 1.3. Can you update and see if it works for you?

**Comment by kcook22** [comment]
Thanks for the response, yes will try the update!

**Comment by JPercival** [comment]
Closing because the question is answered. Feel free to reopen if needed.
