### ISSUE TITLE
DebugResultEntry currently doesn't do anything

### ISSUE THREAD

**Issue by csandersdev** [DBCG/cql_engine#482]
The EvaluationResult class provided as output from the CqlEngine contains a DebugResult class that can be interrogated for details on engine behavior. Digging through there, I noticed that it creates and stores instances of DebugResultEntry, but that class doesn't do anything. It is provided a value as state and then discards the value. Because of this, it is not currently possible to reconstruct the same debug output that is written to stdout during the logDebugResult method.

**Comment by JPercival** [comment]
Took a look but I don't see where it's discarding the value. Could you give me a line number?

**Comment by csandersdev** [comment]
Here is the line I was looking at - https://github.com/DBCG/cql_engine/blob/5be0595637e75d9c89c02a27e505b87e4e7e789a/engine/src/main/java/org/opencds/cqf/cql/engine/debug/DebugResultEntry.java#L8

**Comment by JPercival** [comment]
Thanks! Yeah, I think that ought to be fixed.
