### ISSUE TITLE
Add CQL source code generator

### ISSUE THREAD

**Issue by duncand** [DBCG/cql_engine#49]
It is well established already that we have the Translator project which converts CQL source code to ELM source code, and that we have the CQL Engine project that takes ELM source code and evaluates it to produce result values or other output.

However, I am not aware of any projects that go the other way, either taking ELM and generating CQL, or in particular, an Engine feature that takes an arbitrary in-memory CQL value and generates valid CQL (or ELM) source code that when executed produces the same CQL value.

The task of this ticket is to do the last of these (generating valid CQL source code for an in-memory value), in particular, or otherwise identifying where the functionality already exists.

See also related ticket #40.

The fundamental deliverable of this ticket is characterized by a Java function that takes any Java Object X as input which can be the result of an Executable.evaluate() call, and produce a Java String value consisting of an anonymous valid CQL expression, the E in "define e: E" in Population context, such that subsequent translation and Executable.evaluate() of E would produce a Java Object Y representing a CQL value for which Equivalent(X,Y) would result in true.

One use of this function is that it can be exposed as a CQL "external" function, thus a CQL expression can result in CQL source code, a demonstration of the "external" feature of the language.

Another, very important, use of this function, is that it can be used by the CQL Runner to generate the results displayed back to users.  The current output approximates but doesn't equal valid CQL, so it can't be copy-pasted back into input without manual editing; moreover, the current output may display non-identical values identically.  With the new version, if they display the same / different, they are the same / different respectively.

Note that this ticket is not about generating entire CQL libraries, just individual values; the former if desired (and I think it would be) is the task of another ticket, if not already done.

I estimate that this task can be completed within 1 day of work, given similar features already extant.

**Comment by duncand** [comment]
The third main use of the function is for use in hooking into the IDE debugger.  When debugging the Engine or code using the Engine, when one asks the IDE for the gist of what a variable contains, it can be expressed concisely as CQL source, rather than a big nest of Java objects.  In .Net at least, simply overriding the ToString() method on any object will enable the IDE functionality; I would assume Java IDEs have something similar.

**Comment by JPercival** [comment]
There's now an ELM to CQL generator in the cqf-tooling project:

https://github.com/cqframework/cqf-tooling/blob/a4cc500d7525b4f2df69909019d09d0f01ba97a2/src/main/java/org/opencds/cqf/tooling/cql_generation/drool/visitor/ElmToCqlVisitor.java
