### ISSUE TITLE
Why is there a compile-time dependency on Google FindBugs?

### ISSUE THREAD

**Issue by csandersdev** [DBCG/cql_engine#493]
The [engine/pom.xml](https://github.com/DBCG/cql_engine/blob/2373a5cb21b0289e02deac6f8b1830f104a2041e/engine/pom.xml#L31) has a compile-time dependency on the Google FindBugs project. Since I'm dependent on the engine, I also pull it in. My team flagged this during code review as a questionable dependency, so I'm trying to understand if it is necessary. I can't see any direct reference to the library in the codebase. Can you provide some detail on why this is included as a compile-time dependency? It in a section commented as JAXB-related dependencies in the parent pom.

I tried commenting out this dependency and things started failing because we lost a transitive dependency on javax.annotation. I didn't spend much time after that. I would appreciate any thoughts you have on this.

**Comment by JPercival** [comment]
Is your team's concern that the dependency exists at all or is it simply the fact that it's out of date? "findbugs" is now "spotbugs" and we'd need to update. The new version is a build plugin that doesn't add a compile-time dependency so that might resolve the issue either way.

**Comment by csandersdev** [comment]
It is the fact that the JAR ends up in our runtime classpath when it seems like it should be a build-time artifact only. If the engine used it strictly through the build plugin and removed it from the compile classpath that would resolve the issue. I just wasn't sure if there was some weird reason why the engine was including it as a compile dependency. If not, I can do some dependency management tricks to get rid of it on my end.

**Comment by JPercival** [comment]
No reason that I'm aware of. Feel free to get tricky.
