### ISSUE TITLE
e500 in DMS Measure Evaluation

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cql_engine#54]
Linking to this issue [e500 in DMS Measure](https://github.com/DBCG/cqf-ruler/issues/32) which includes a suggested patch too

**Comment by c-schuler** [comment]
Fix for this issue is included in https://github.com/DBCG/cql_engine/pull/58 pull request.

**Comment by jeffeastman** [comment]
Closing this as the errors no longer appear. I am getting (the same) strange denominators for DMS. I think this is because IPP is not a factor in the denominator CQL. I'll open a separate issue for that.

===== In-memory Summary =====
	denominator 1 = 100
	denominator 2 = 100
	denominator 3 = 100
	initial-population = 55
	numerator 1 = 83
	numerator 2 = 55
	numerator 3 = 25

===== Server Summary =====
	denominator 1 = 100
	denominator 2 = 100
	denominator 3 = 100
	initial-population = 55
	numerator 1 = 83
	numerator 2 = 55
	numerator 3 = 25

**Comment by c-schuler** [comment]
Did you mean to close this?

**Comment by jeffeastman** [comment]
Yes, because its working
