### ISSUE TITLE
ThreadLocal storage in the engine

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#565]
The use of ThreadLocal storage in the cql-engine is causing issues when running CQL in parallel. The default Java task scheduler is such that the thread executing the CQL may not be the same thread the Context was initialized on. For example, you may create a ThreadPool with 8 threads, and 100 different contexts, and those are allocated across all those threads.

Honestly this sounds like a bug in the Java task scheduler to me, the contract for ThreadLocal is that it's, well, ThreadLocal, so not having the access synchronized to the same thread seems like a pretty clear violation of that contract. But that's not something we have control over.

**Comment by JPercival** [comment]
Not a bug in the contract for ThreadLocal. The ThreadLocal contract is related to hardware threads, as opposed to software fibers/coroutines/continuations. The CompletableFutures framework allows scheduling tasks on a main thread, which may then be processed on "background" threads. By default a queue is created for each hardware thread, and the queue is processed sequentially. If another thread finishes first, it can "steal" work from another thread's queue.

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html

**Comment by JPercival** [comment]
IOW, the current implementation works fine if the user handles all the creation of Threads themselves. It doesn't work when the Java infrastructure is allowed to do that for you.

**Comment by JPercival** [comment]
Here's a nice explanation of the issue too:
https://www.baeldung.com/java-threadlocal#threadlocalsand-thread-pools

**Comment by brynrhodes** [comment]
Included in 1.5.7 release
