### ISSUE TITLE
Count of Query source returns null if query return one result

### ISSUE THREAD

**Issue by nkarip** [DBCG/cql_engine#6]
I am counting results of a query operation and latest snapshot is causing errors in cases where the query only returns one result. The QueryEvaluator is now returning a single object instead of an iterable object with one member, which is what I was expecting. CountEvaluator is returning null because the source expression result is not iterable. 

Is this intended behavior? In that case, how would the Count expression have to be written to handle a source query which may return 0 or more results?

Also, it seems like the code will throw an indexoutofboundsexception if the query returns 0 results, based on lines 122 and 130 of QueryEvaluator.

**Comment by c-schuler** [comment]
Resolved in commit https://github.com/DBCG/cql_engine/commit/9941203d031ebd0a4bef93db2b6e47d2560a288e
