### ISSUE TITLE
Task -> Patient path returns `requester` and not `for`

### ISSUE THREAD

**Issue by vitorpamplona** [DBCG/cql_engine#621]
[LibraryProcessor.evaluate](https://github.com/DBCG/cql-evaluator/blob/fe7fdfb87be8f94a9b64351c9642a5adb7bfbca6/evaluator.library/src/main/java/org/opencds/cqf/cql/evaluator/library/LibraryProcessor.java#L140) takes a `patientID`. That value is automatically mapped to the first `contextPath` in the list of HAPI's Children annotations where `$dataType.$contextPath => $contextType`. 

But what happens when the `dataType` requested has multiple contextPaths to `contextType`?

Task is a good example. There are 4 fields that link it with Patient: `requester`, `owner`, `for`, and `recipient`. Which one should the `LibaryProcessor` use as `PatientId`? My first instinct is an `OR` with all of them. But as currently coded, the [R4FhirModelResolver.getContextPath](https://github.com/DBCG/cql_engine/blob/5a280f58486a1b3366f729d464d52cc9a37e7d59/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/model/R4FhirModelResolver.java#L350) method simply returns the first reference it finds to `Patient`. For the `Task`, it gets a `requester`. 

Which is not what we want. `for` would be a more appropriate result if we are just using one of them.

**Comment by vitorpamplona** [comment]
We could hardcode another exception in the [R4FhirModelResolver.getContextPath](https://github.com/DBCG/cql_engine/blob/5a280f58486a1b3366f729d464d52cc9a37e7d59/engine.fhir/src/main/java/org/opencds/cqf/cql/engine/fhir/model/R4FhirModelResolver.java#L350)

from:
```java
    public Object getContextPath(String contextType, String targetType) {
        if (targetType == null || contextType == null ) {
            return null;
        }

        if (contextType.equals("Patient") && targetType.equals("MedicationStatement")) {
            return "subject";
        }

        return super.getContextPath(contextType, targetType);
    }
```

to:
```java
    public Object getContextPath(String contextType, String targetType) {
        if (targetType == null || contextType == null ) {
            return null;
        }

        if (contextType.equals("Patient") && targetType.equals("MedicationStatement")) {
            return "subject";
        }
        
        if (contextType.equals("Patient") && targetType.equals("Task")) {
            return "for";
        }

        return super.getContextPath(contextType, targetType);
    }
```

But this feels very wrong.

**Comment by JPercival** [comment]
There are a couple considerations here. One is the definition of the `Patient` compartment in FHIR, which defines the set of things that are related to a Patient. It's not 100% solid though. See the discussion here:

https://chat.fhir.org/#narrow/stream/179220-cql/topic/How.20does.20CQL.20'data.20model'.20match.20perform.20context.20matching.3F

The resolution that was suggested was to define a `primaryContextPath`. There's an issue tracking that here:
https://github.com/cqframework/clinical_quality_language/issues/710
