### ISSUE TITLE
After and Before comparisons are being done for ONLY the specified precision

### ISSUE THREAD

**Issue by c-schuler** [DBCG/cql_engine#66]
Instead of comparing DateTime/Time values UP TO the specified precision as the spec states, the Engine is only comparing the values specified by the precision.

For example, the following expressions evaluate to false when they should be evaluate to true:
```
define AfterTest: @2010-12-10 after day of @2009-12-12
define BeforeTest: @2009-12-10 before day of @2010-12-09
```

**Comment by duncand** [comment]
I have confirmed that pull request #67 fixes the concerns of this issue, and also doesn't seem to have introduced any new test suite errors.
