### ISSUE TITLE
Code Equivalence needs to be updated based on Errata

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cql_engine#70]
Code equivalence was relaxed in an errata update to CQL to ignore version, but the engine is still considering it for equivalence:

    define C1: 
      Code { 
        code: 'ABC',
        display: 'Code ABC',
        system: 'http://example.com',
        version: '2017-01'
      }

    define C2:
      Code {
        code: 'ABC',
        display: 'Variant Description',
        system: 'http://example.com',
        version: '2017-05'
      }

    define CEqual: C1 = C2 // false
    define CEquivalent: C1 ~ C2 // true

**Comment by c-schuler** [comment]
Addressed in #93
