### ISSUE TITLE
Modify provider to not put the type in query if it's a no-op

### ISSUE THREAD

**Issue by nkarip** [DBCG/cql_engine#8]
Open Epic test FHIR server does not support query of type below for patient retrieval.
https://open-ic.epic.com/FHIR/api/FHIR/DSTU2/Patient?_id=Patient/Tbt3KuCY0B5PSrJvCu2j-PlK.aiHsu2xUjUM8bWpetXoB
Does support following format, without "=Patient/".
https://open-ic.epic.com/FHIR/api/FHIR/DSTU2/Patient?_id=Tbt3KuCY0B5PSrJvCu2j-PlK.aiHsu2xUjUM8bWpetXoB

Per Bryn, could improve the provider to not put the type in if it's a no-op.

**Comment by c-schuler** [comment]
Fixed here:
https://github.com/DBCG/cql_engine/commit/f78043e2bfcb572b257a744addda8d055c22a07f
