### ISSUE TITLE
Check the bundle entry resourceType matches requested type in the Retrieve operation results

### ISSUE THREAD

**Issue by nkarip** [DBCG/cql_engine#9]
Open Epic FHIR server returns Operation Outcome with message "Resource request returns no results", rather than empty bundle, when query has 0 results. Causes errors in Query operations due to type mismatch, unless resource type is always explicitly checked.

Suggest enhancement to check the Bundle entry resourceType and only include those that match the requested type in the Retrieve operation results.

**Comment by c-schuler** [comment]
Fixed here:
https://github.com/DBCG/cql_engine/commit/7666186b16139eec0b84d08dd0811aba55dc8ab1
